# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: ['**']

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
      - run: npm run prettier-check
      - name: Make sure open-api.ts on the client side matches backend API
        run: |
          cd frontend
          npm run gen:api
          cd ../
          npm run prettier
          if git status -s | grep frontend/src/api/open-api.ts > /dev/null; then
              echo "open-api.ts was modified by the "npm run gen:api" command. Run it locally, and commit the changes."
              exit 1
          fi
